name: $(date:yyyy.MM.dd)$(rev:.r)

trigger:
  batch: true
  branches: 
    include: 
      - main
  paths:
    include:
      - /Innovian.Aspects.Logging
      - /Innovian.Aspects.Logging.Testing

pool: AzureBuildServers

workspace:
  clean: all

variables:
  - name: BuildNumber
    value: $(Build.BuildNumber)
  - name: ProjectName
    value: Innovian.Aspects.Logging

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/$(ProjectName).csproj'
    noCache: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/$(ProjectName).csproj'
    arguments: '--no-restore'

# Aspect testing
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/$(ProjectName).Testing.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/$(ProjectName).csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BuildNumber'

- task: PowerShell@2
  displayName: 'push to NuGet.org'
  inputs:
    targetType: 'inline'
    script: 'nuget push "$(Build.ArtifactStagingDirectory)\*.nupkg" -ApiKey $(NuGetApiKey) -Source https://api.nuget.org/v3/index.json'
  env:
    NuGetApiKey: $(NuGetApiKey)